version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: meu_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nickciuffi
      MONGO_INITDB_ROOT_PASSWORD: Niisaricris1
    volumes:
      - ./data:/data/db
