spring.application.name=cutia
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ambiente-iot
spring.data.mongodb.username=nickciuffi
spring.data.mongodb.password=Niisaricris1
spring.data.mongodb.authentication-database=admin

